name: Run ML Pipeline  # This names the workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:  
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting code..."

      - name: Run unit test
        run: echo "Running unit test..."

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run main.py
        run: |
          echo "Running with DAGSHUB_TOKEN: ${DAGSHUB_TOKEN:0:4}****"
          python main.py